# プロジェクト自動化設定

labels:
  - name: "task"
    color: "0075ca"
    description: "タスクや作業項目"
  - name: "enhancement"
    color: "a2eeef"
    description: "新機能や改善"
  - name: "bug"
    color: "d73a49"
    description: "バグや問題"
  - name: "project-management"
    color: "ededed"
    description: "プロジェクト管理関連"
  - name: "automation"
    color: "ededed"
    description: "自動化関連"
  - name: "documentation"
    color: "0052cc"
    description: "ドキュメント関連"
  - name: "priority-high"
    color: "d93f0b"
    description: "高優先度"
  - name: "priority-medium"
    color: "fbca04"
    description: "中優先度"
  - name: "priority-low"
    color: "0e8a16"
    description: "低優先度"

project_columns:
  - name: "Todo"
    automation: "issues_opened"
  - name: "In Progress"
    automation: "issues_assigned"
  - name: "Done"
    automation: "issues_closed"

automation_rules:
  - type: "issue_opened"
    action: "add_to_project"
    column: "Todo"
  - type: "issue_assigned"
    action: "move_to_column"
    column: "In Progress"
  - type: "issue_closed"
    action: "move_to_column"
    column: "Done"
  - type: "pr_opened"
    action: "add_to_project"
    column: "In Progress"
  - type: "pr_merged"
    action: "move_to_column"
    column: "Done"